### ISSUE TITLE
[image] 이미지 파일 로직 수정

### ISSUE THREAD

**Issue by kim-ju-ho** [petpat-co/petpat-co-back#19]
### 이미지 파일 로직 수정

```    @Transactional
    public List<String> updateImage(List<MultipartFile> multipartFiles, Long postId, PostType postType) {
        List<String> fakeFiles = imageUploader.createKey(postId, postType);
        for (String fakeFile :fakeFiles) {
            imageUtils.getFileExtension(fakeFile);
        }
        s3Uploader.deleteS3(fakeFiles,postId, postType);
        imageUploader.deleteImg(postId, postType);
        return uploadPostImage(multipartFiles, postId, postType);
    }
```

해당 확장자 체크로직인 `  imageUtils.getFileExtension(fakeFile);`이 부분에서 ` uploadPostImage(multipartFiles, postId, postType);`
호출 하고 있으므로 중복되어 호출되는것으로 보입니다.  따라서 해당 로직의 삭제가 필요해 보입니다. 
다른 의견있으시면 공유부탁드립니다.

**Comment by kim-ju-ho** [comment]
해당 로직의 ``@Transactional`` 부분도 확인결과 현재 S3부분에서의  ``@Transactional``처리가 이루어지지 않기 떄문에 의미가 없는걸로 보여집니다. 확인 후 삭제 부탁드립니다.

**Comment by ohyeryung** [comment]
1. 해당 부분은 db 에 저장된 이미지를 삭제하는 메소드가 실행되기 전에 확장자 체크로직을 미리 할 수 있도록 한 것인데 
` uploadPostImage(multipartFiles, postId, postType);` 부분에서 체크해도 db 이미지가 삭제되지 않는 것 확인했습니다.  
다만 S3 에 올라간 기존 이미지를 지우기 위해서 key 값인 fakeFileName 이 필요하기 때문에 아래 코드대로 수정하는 게 좋다고 생각합니다!

```
public List<String> updateImage(List<MultipartFile> multipartFiles, Long postId, PostType postType) {
        List<String> fakeFiles = imageUploader.createKey(postId, postType);
        s3Uploader.deleteS3(fakeFiles,postId, postType);
        imageUploader.deleteImg(postId, postType);
        return uploadPostImage(multipartFiles, postId, postType);
    }
```

2. 네 저도 S3부분에서의 `@Transactional`처리가 이루어지지 않기 때문에 의미가 없다고 생각합니다. 삭제 하겠습니다.

**Comment by kim-ju-ho** [comment]
수정 확인했습니다.
