### ISSUE TITLE
[image] 게시물 상세조회 중 이미지리스트 조회 시 대표이미지 설정 문제

### ISSUE THREAD

**Issue by kim-ju-ho** [petpat-co/petpat-co-back#70]
## 현재
```
 @Transactional
    public List<String> createImgList(Long postId, PostType postType) {
        List<Image> images = imageRepository.findAllByPostIdAndPostType(postId, postType);
        return images.stream().map(Image::getFilePath).collect(Collectors.toList());
    }
```
###  해당 코드로 진행했을 때의 문제점

- 이미지를 뽑는 로직이 JPA상 `findAllByPostIdAndPostType` 이렇게 되어있는 점으로 보았을때, 순서 보장이 안되고 있는 상태입니다.
인덱스 기준으로 가장 먼저 뽑는다면 `orderBy`를 추가하여, 정렬이 필요해보이는 부분입니다. 또한 대표이미지 구별 컬럼을 추가한 시점에서 프론트로 전달하는 JSON 포맷 변환도 생각해봐야할거 같습니다. 

- 현재 서비스의 이미지 업로드 갯수가 5개로 한정되어있는 점으로 보았을때 조회 시 5개 제한으로 뽑는 방법도 고려해봐야 할 부분입니다.

**Comment by ohyeryung** [comment]
네 순서정렬이 필요해보이네요. 추가해서 수정해보겠습니다! 👍

**Comment by ohyeryung** [comment]
수정 완료하였습니다
